# Cloud development environment
# TODO: Create the dev environment.

[api]
host = "0.0.0.0"
port = 8080
base_url = "https://dev.tokenoverflow.io"
request_timeout_secs = 30

[auth]
workos_client_id = "client_xxx"
workos_api_url = "https://api.workos.com"
jwks_url = "https://<authkit_domain>/oauth2/jwks"
jwks_cache_ttl_secs = 3600
issuer = "https://auth.workos.com/xxx"
audiences = ["https://dev.tokenoverflow.io"]
authkit_url = "https://intimate-figure-17.authkit.app"
github_api_url = "https://api.github.com"
github_client_id = "Ov23lifpB2PCzk8nmdni"

[database]
host = "main-dev.xxxx.us-east-1.rds.amazonaws.com"
port = 5432
user = "tokenoverflow"
name = "tokenoverflow"

[embedding]
base_url = "https://api.voyageai.com/v1"
model = "voyage-code-3"
output_dimension = 256

[mcp]
base_url = "https://dev.tokenoverflow.io/mcp"

[logging]
level = "info"
