version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule: { interval: weekly }
      groups:
          workflow-actions:
              patterns: ["*"]
    - package-ecosystem: github-actions
      directories:
          - /.github/actions/bun_install
          - /.github/actions/rust_toolchain
          - /.github/actions/docker_compose_up
          - /.github/actions/playwright_install
      schedule: { interval: weekly }
      groups:
          composite-action-internals:
              patterns: ["*"]
