version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule: { interval: weekly }
      groups:
          workflow-actions:
              patterns: ["*"]
    - package-ecosystem: github-actions
      directories:
          - /.github/actions/*
      schedule: { interval: weekly }
      groups:
          composite-action-internals:
              patterns: ["*"]
