name: local
variables:
  - name: base_url
    value: http://localhost:8080
  - name: access_token
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJzdWIiOiJzeXN0ZW0iLCJpc3MiOiJ0b2tlbm92ZXJmbG93LXRlc3QiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJpYXQiOjE3NzM5MDk4OTgsImV4cCI6MjA4OTI2OTg5OH0.e4AMklpjLZlnu9jl1tc1aQdfyAiWRkykvtATZ8GEiiL3o3ibu_wclWqdN2w7yv7ReVfT8XZ9nAKPmwzFfoqk7y23lp1FMAIMSS_AVDd3uGIrC4iHGe-8_OyQIiW9aWIQbqgwTQA-JwWcmCVZTejbR55XAtcgoGKm8IB6NFINszBr96Yi4Cnd-OYT846C4hs0JoHXQmtkislkl7-FgAuJFiX2DHr589bs7kVVG9Lt4YqOgG5z5N-Prqg70sJD8K8jZVtvuyOKI31Mvw3cLTAdZwFodOuYLxaHDEdopn1Y_RDL44g3IMOjgO0AjYbvVkF6I7I_iJPyo72EcZEZtrTLHg
