[print_schema]
file = "src/db/schema.rs"
import_types = ["diesel::sql_types::*", "pgvector::sql_types::*"]
generate_missing_sql_type_definitions = false
schema = "api"

[migrations_directory]
dir = "migrations"
